### ISSUE TITLE
No way of specifying path to the cabal file.

### ISSUE THREAD

**Issue by VenInf** [Bodigrim/cabal-add#6]
The `cabal-add` tool looks up the cabal file by searching the current working directory.
I want to add the cabal-add tool to the hls and it would be very beneficial to have a way of specifying the path to the cabal file.
To my understanding, the `--project-file` is not related to this request (and also I failed to make this option work in this scenario).

**Comment by Bodigrim** [comment]
Thanks for the report, I've just pushed some fixes for `--project-file`. Is it any better now?

If you want to add `cabal-add` to HLS, I'd suggest using API instead of calling an executable: https://hackage.haskell.org/package/cabal-add-0.1/candidate/docs/Distribution-Client-Add.html. It allows to specify an explicit Cabal file, [`parseCabalFile`](https://hackage.haskell.org/package/cabal-add-0.1/candidate/docs/Distribution-Client-Add.html#v:parseCabalFile).

**Comment by VenInf** [comment]
Thank you for the fix!
Now `--project-file` works with both relative and absolute paths to the `cabal.project` file. I wonder, is there a way to specify just a cabal file by itself without using API.

I wanted to make a solution using just API at first, but had trouble creating an input for the `executeConfig`. I will try this route once again.

**Comment by Bodigrim** [comment]
> I wonder, is there a way to specify just a cabal file by itself without using API.

This is not planned. The reason is that `cabal-add` is supposed to be used as [Cabal external command](https://cabal.readthedocs.io/en/latest/external-commands.html) and as such follows Cabal design decisions. Cabal does not allow you to pass `*.cabal` file, only `cabal.project`, so `cabal-add` behaves similarly.

> I wanted to make a solution using just API at first, but had trouble creating an input for the `executeConfig`. I will try this route once again.

In a nutshell you can do something like this:

https://github.com/Bodigrim/cabal-add/blob/0cb197d7cf31630c2e61f59d9a14f1c0a00af971/app/Main.hs#L81-L97

Feel free to ask questions or ping me in HLS issue. 

Once you get a prototype working, I'll be happy to make a Hackage release to simplify setup.

**Comment by VenInf** [comment]
> Cabal does not allow you to pass *.cabal file, only cabal.project, so cabal-add behaves similarly.

I didn't know that. Thank you for the explanation!

Thank you for the pointers on the `Config` usage, it will help.
I'll let you know once I have a working proof-of-concept solution.
